#!/bin/bash

mvn clean install

if [[ ! -f target/openapi-docs/openapi.json ]]
then
    echo "#########################################"
    echo "No openapi.json file found : getting it" && mvn endpoints-framework:openApiDocs
    echo "#########################################"
fi

gcloud endpoints services deploy target/openapi-docs/openapi.json
